lib/multi_tenancex_web/router.ex
defmodule MultiTenancexWeb.Router do
  use MultiTenancexWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :browser_auth do
    plug(MultiTenancexWeb.Guardian.AuthPipeline)
    plug(MultiTenancexWeb.Plug.CurrentAdmin)
    plug(MultiTenancexWeb.Plug.CurrentTenant)
  end

  pipeline :browser_ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
    plug(MultiTenancexWeb.Plug.CurrentAdmin)
    plug(MultiTenancexWeb.Plug.CurrentTenant)
  end

  pipeline :admin_layout do
    plug(:put_layout, {MultiTenancexWeb.Admin.LayoutView, :admin})
  end

  scope "/", MultiTenancexWeb do
    # Application unauthenticated scope
    scope "/" do
      pipe_through([:browser, :browser_auth])

      get("/", PageController, :index)

      resources("/session", SessionController, only: [:new, :create])

      # Log out resource
      get("/logout", SessionController, :delete)
    end

    # Admin scope
    scope "/admin", Admin, as: :admin do
      pipe_through([
        :browser,
        :browser_auth,
        :browser_ensure_auth,
        :admin_layout
      ])

      # Switch tenant resource
      post("/switch_tenant", DashboardController, :switch_tenant)

      resources("/", DashboardController, only: [:index])
      resources("/administrators", AdministratorController)
      resources("/companies", CompanyController)
      resources("/products", ProductController)
    end
  end
end

lib/multi_tenancex_web/views/admin/layout_view.ex
defmodule MultiTenancexWeb.Admin.LayoutView do
  alias MultiTenancex.TenantActions

  use MultiTenancexWeb, :view

  def select_tenant_options do
    TenantActions.list_tenants(MultiTenancex.Repo)
  end
end

lib/multi_tenancex_web/views/layout_view.ex
defmodule MultiTenancexWeb.LayoutView do
  use MultiTenancexWeb, :view
end

lib/multi_tenancex_web/templates/layout/_flash_messages.html.eex
<%= if get_flash(@conn, :info) do %>
  <div class="alert alert-primary"> <%= get_flash(@conn, :info) %> </div>
<% end %>

<%= if get_flash(@conn, :error) do %>
  <div class="alert alert-danger"> <%= get_flash(@conn, :error) %></span> </div>
<% end %>

lib/multi_tenancex_web/templates/layout/_navbar.html.eex
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link gettext("MultiTenancex"), to: page_path(@conn, :index), class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav">
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link gettext("Admin"), to: admin_dashboard_path(@conn, :index), class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

lib/multi_tenancex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= gettext("MultiTenancex") %></title>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
    <meta name="keywords" content="" />
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <%= render("_navbar.html", assigns) %>
    <div class="container">
      <main role="main">
        <%= render("_flash_messages.html", assigns) %>
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
    <%= render("_footer.html", assigns) %>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>